name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - run: npm i
      - run: npm run build --if-present
      - run: cp -fR /home/ysn/Documents/actions-runner/react-app/react-gh-actions/react-gh-actions /var/www/html/

